name       : freecell-solver
version    : 5.16.0
release    : 2
source     :
    - https://fc-solve.shlomifish.org/downloads/fc-solve/freecell-solver-5.16.0.tar.xz : 7f12dc75d23493c57ec966de8d05ede18d934c597494e1cb30052c6f08808f65
license    : MIT
homepage   : https://fc-solve.shlomifish.org
component  : programming
summary    : C library for solving Freecell and similar games
description: |
    Freecell Solver is a library, written in C, for attempting to solve several variants of card Solitaire/Patience including Freecell, Baker’s Game, Seahaven Towers and Simple Simon.
builddeps  :
    - pkgconfig(librinutils)
    - gperf
    - perl-path-tiny
    - perl-template
    - python-pysol-cards
setup      : |
    # The test suite needs unpackaged dependencies
    %cmake_ninja -DBUILD_STATIC_LIBRARY=OFF \
        -DDISABLE_APPLYING_RPATH=ON \
        -DFCS_AVOID_TCMALLOC=ON \
        -DFCS_WITH_TEST_SUITE=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Remove README file
    rm -rf $installdir/usr/share/doc
