name       : freecell-solver
version    : 6.8.0
release    : 7
source     :
    - https://fc-solve.shlomifish.org/downloads/fc-solve/freecell-solver-6.8.0.tar.xz : 95f78a4b15d2fa340271fe4fcc5354065968191ba22db0d40e81b291b8d53d32
license    : MIT
homepage   : https://fc-solve.shlomifish.org
component  : programming.library
summary    : C library for solving Freecell and similar games
description: |
    Freecell Solver is a library, written in C, for attempting to solve several variants of card Solitaire/Patience including Freecell, Baker’s Game, Seahaven Towers and Simple Simon.
builddeps  :
    - pkgconfig(librinutils)
    - gperf
    - perl-moo
    - perl-path-tiny
    - perl-template
    - python-pysol-cards
setup      : |
    # The test suite needs unpackaged dependencies
    %cmake_ninja -DBUILD_STATIC_LIBRARY=OFF \
        -DDISABLE_APPLYING_RPATH=ON \
        -DFCS_AVOID_TCMALLOC=ON \
        -DFCS_WITH_TEST_SUITE=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Remove README file
    rm -rf $installdir/usr/share/doc
