name       : freecell-solver
version    : 5.14.0
release    : 1
source     :
    - https://fc-solve.shlomifish.org/downloads/fc-solve/freecell-solver-5.14.0.tar.xz : b09e7394181fcd972436fbbcd2192a9085b8924b70c892ad88b9ad95a7abee12
license    : MIT
component  : programming
summary    : C library for solving Freecell and similar games
description: |
    Freecell Solver is a library, written in C, for attempting to solve several variants of card Solitaire/Patience including Freecell, Baker’s Game, Seahaven Towers and Simple Simon.
builddeps  :
    - gperf
    - perl-path-tiny
    - perl-template
    - python-pysol-cards
setup      : |
    # The test suite needs unpackaged dependencies
    %cmake_ninja -DBUILD_STATIC_LIBRARY=OFF \
        -DDISABLE_APPLYING_RPATH=ON \
        -DFCS_AVOID_TCMALLOC=ON \
        -DFCS_WITH_TEST_SUITE=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Remove README file
    rm -rf $installdir/usr/share/doc
