name       : freecell-solver
version    : 5.20.1
release    : 3
source     :
    - https://fc-solve.shlomifish.org/downloads/fc-solve/freecell-solver-5.20.1.tar.xz : 339339a47b1842624ea9e322e4fe5af5a48a63310571595ca00b0b03f6f25524
license    : MIT
homepage   : https://fc-solve.shlomifish.org
component  : programming.library
summary    : C library for solving Freecell and similar games
description: |
    Freecell Solver is a library, written in C, for attempting to solve several variants of card Solitaire/Patience including Freecell, Baker’s Game, Seahaven Towers and Simple Simon.
builddeps  :
    - pkgconfig(librinutils)
    - gperf
    - perl-path-tiny
    - perl-template
    - python-pysol-cards
setup      : |
    # The test suite needs unpackaged dependencies
    %cmake_ninja -DBUILD_STATIC_LIBRARY=OFF \
        -DDISABLE_APPLYING_RPATH=ON \
        -DFCS_AVOID_TCMALLOC=ON \
        -DFCS_WITH_TEST_SUITE=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Remove README file
    rm -rf $installdir/usr/share/doc
